### ISSUE TITLE
issues in current version

### ISSUE THREAD

**Issue by mukeshwebs** [EthanZoneCoding/HolepunchDisplay#1]
1. app keeps stopping in between many times 
2. when dynamic island zoom to display the content the text overlays other text and app icon image is shown larger, i would suggest to make it responsive.

**Comment by EthanZoneCoding** [comment]
1 is being worked on,
2 has to do with too long text. I have a limiter but the threshold is too high.

**Comment by mukeshwebs** [comment]
try making popup.xml responsive

**Comment by EthanZoneCoding** [comment]
The app has new error handling, this should improve stopping. The text  limit was fixed. Responsive popup will be noted as an enhancement.
