### ISSUE TITLE
major issue after allowing all permissions

### ISSUE THREAD

**Issue by mukeshwebs** [EthanZoneCoding/HolepunchDisplay#2]
![image](https://user-images.githubusercontent.com/53649320/190910874-387a5774-88ce-4815-b9a1-16956042b1ea.png)

After giving all the asked permission the top area is getting deactivated and it become irresponsive, it deactivates the touch there.
please fix this

**Comment by EthanZoneCoding** [comment]
Does this affect the island or just the UI behind it?

**Comment by mukeshwebs** [comment]
the area shown red in the screenshot is not responsing on touch after giving accessibility permission.
the dynamic island was active in my app and i opened play store and tried searching something but touch in that area is not working due to this dynamic island.

I guess when after receiving some notification the bigger view area of dynamic island is shown and that all area is making touches responsive. 
fix it somehow, btw i'm looking forward to contribute to this project.

**Comment by EthanZoneCoding** [comment]
The popup window changes size to fit the island, otherwise the island becomes cropped. I will probably need to integrate it into the calibration

**Comment by mukeshwebs** [comment]
but after giving accessibility permission it doesn't allow to touch in that area.
it's  a must fix otherwise it won't be feasible

**Comment by EthanZoneCoding** [comment]
The accessibility perms really just let's the popup window show over the
status bar. The island is in the window. If the window is too small for the
island, the edges won't show. If it's too big, it blocks too much touch on
the screen. It just needs to be calibrated, which hasn't been implemented
yet. You can change the window width and height in the layoutparams.

**Comment by mukeshwebs** [comment]
Cool.
When u are planning to calibrate

**Comment by EthanZoneCoding** [comment]
As soon as I can. Maybe today or tomorrow. I'll also be adding charging
animations, unrestricted battery permissions, better error handling, and
other improvements.

**Comment by EthanZoneCoding** [comment]
Fixed in v0.0.3alpha
