### ISSUE TITLE
Issues. And improvement suggestions.

### ISSUE THREAD

**Issue by JayKing21** [EthanZoneCoding/HolepunchDisplay#3]
Can you make the idle part same size as hole punch camera and also adjustable for other devices that have camera either end or middle of screen. Also when I click the idle part and the big pop-up show it just completely black. Not seeing anything.

**Comment by EthanZoneCoding** [comment]
What device? Left and right support is planned, I'll add support for just
dot form when not expanded.

**Comment by JayKing21** [comment]
Samsung galaxy A32 4g

**Comment by EthanZoneCoding** [comment]
Better calibration options were added in v0.0.3alpha.
